### ISSUE TITLE
Automatic relogin after disconnect

### ISSUE THREAD

**Issue by timo-schluessler** [nim65s/matrix-webhook#134]
When connection to matrix server is lost, the webhook should automatically reconnect and re-login. The function `join_room` seems to be meant to re-login automatically, but in my case at least it doesn't, because `CLIENT.join()` doesn't return with the expected `JoinError` but in fact throws (see https://github.com/matrix-nio/matrix-nio/issues/487).
Should this be worked around or fixed upstream?

**Comment by nim65s** [comment]
fixed in #135
