### ISSUE TITLE
Can't handle special "Consent" flows

### ISSUE THREAD

**Issue by w4tsn** [nim65s/matrix-webhook#15]
Using this webhook bot on an instance (hosted via Element.io) with custom Consent flows the bot errors out with an unhandled exception:

```
alertbot_1  | 2021-10-12 11:50:45,698 - aiohttp.server - 393 - ERROR - Error handling request
alertbot_1  | Traceback (most recent call last):
alertbot_1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
alertbot_1  |     resp = await self._request_handler(request)
alertbot_1  |   File "/matrix_webhook/handler.py", line 85, in matrix_webhook
alertbot_1  |     return await utils.send_room_message(data["room_id"], content)
alertbot_1  |   File "/matrix_webhook/utils.py", line 40, in send_room_message
alertbot_1  |     ERROR_MAP[resp.status_code], resp.message
alertbot_1  | KeyError: 'M_CONSENT_NOT_GIVEN'
```

On this instance a newly created user (in this case the bot user) is redirected to a consent page and has to accept it before being able to participate and join rooms.

If not easily fixable (navigating and accepting to consent pages will probably be hard) this error should at least be printed to the log, even without the `--verbose` flag.

**Comment by nim65s** [comment]
We could add `M_CONSENT_NOT_GIVEN` to the error map, and indicate that the user must manually give the bot's consent. Would this work for you ?
