### ISSUE TITLE
New Grafana notifications not formatted correctly

### ISSUE THREAD

**Issue by svenseeberg** [nim65s/matrix-webhook#29]
The recent update of Grafana revamps the whole notification system, including a changed format. In my case the formatting of the message is lost and looks like this:

![image](https://user-images.githubusercontent.com/15197000/175873909-7a2c17a1-c717-4bad-99ed-01d7cb0d2912.png)

It should probably look like this:

![image](https://user-images.githubusercontent.com/15197000/175874077-13ce3857-2d67-4f4e-b57f-5793936025e1.png)

I'm currently investigating why this is happening and will probably contribute a PR when I found the issue.

**Comment by nim65s** [comment]
Thanks !
We'll probably need compatibility with the 2 versions :(

**Comment by YourSandwich** [comment]
Hi, any progress with it? Has this something to do with the webhook or grafana itself?

**Comment by svenseeberg** [comment]
Sadly I have not yet found time for this. I will eventually look the problem. There is no clear answer to the question. The problem is due to the changed message. In the end this application here has to make sure that the messages are translated correctly.

**Comment by nim65s** [comment]
Maybe you can start by providing a JSON file similar to https://github.com/nim65s/matrix-webhook/blob/master/tests/example_grafana.json for the newer version ? This should unlock discussions, and potential contributions from others

**Comment by svenseeberg** [comment]
The messages from Grafana 9.x look like this:
```
{'receiver': '', 'status': 'firing', 'alerts': [{'status': 'firing', 'labels': {'alertname': 'TestAlert', 'instance': 'Grafana'}, 'annotations': {'summary': 'Notification test'}, 'startsAt': '2022-09-07T14:34:59.055075255+02:00', 'endsAt': '0001-01-01T00:00:00Z', 'generatorURL': '', 'fingerprint': '57c6d9296de2ad39', 'silenceURL': 'https://grafana.example.com/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DTestAlert&matcher=instance%3DGrafana', 'dashboardURL': '', 'panelURL': '', 'valueString': "[ metric='foo' labels={instance=bar} value=10 ]"}], 'groupLabels': {}, 'commonLabels': {'alertname': 'TestAlert', 'instance': 'Grafana'}, 'commonAnnotations': {'summary': 'Notification test'}, 'externalURL': 'https://grafana.example.com/', 'version': '1', 'groupKey': '{alertname="TestAlert", instance="Grafana"}2022-09-07 14:34:59.055075255 +0200 CEST m=+245053.296567153', 'truncatedAlerts': 0, 'orgId': 1, 'title': '[FIRING:1]  (TestAlert Grafana)', 'state': 'alerting', 'message': "**Firing**\n\nValue: [ metric='foo' labels={instance=bar} value=10 ]\nLabels:\n - alertname = TestAlert\n - instance = Grafana\nAnnotations:\n - summary = Notification test\nSilence: https://grafana.example.com/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DTestAlert&matcher=instance%3DGrafana\n", 'key': '8NNiOzrjXv94pIHn34qhBxy4ZDzNiki8'}
```
