### ISSUE TITLE
[question] intended posts to be unencrypted?

### ISSUE THREAD

**Issue by aspann** [nim65s/matrix-webhook#32]
Is it intended to push the messages unencrypted? 
(or did I just miss something?)

Btw. good work! :+1:

**Comment by nim65s** [comment]
Hi,

Well, they are encrypted over HTTPS, from the webhook client to this matrix-webhook server if this is deployed properly, but not in the matrix sense.

The underlying lib [matrix-nio](https://github.com/poljar/matrix-nio) support matrix encryption, so it should be possible to send encrypted messages if necessary :)

**Comment by aspann** [comment]
Hi,
thanks for the quick response! 

I know that the transport-layer is encrypted, it was more about the encrypted messaging via matrix-nio (but it seems to be unimplemented) into the desired room. Have you any plans to implement it?

**Comment by nim65s** [comment]
I don't have plans to implement it. 

If you can contribute, this will be welcome !

**Comment by aspann** [comment]
Nice, if I got something I'll open a PR/Issue.
Until then I'll close this for now. 

cheers.
